### ISSUE TITLE
Could you please upload the code of how to generate train/test.ast.src 

### ISSUE THREAD

**Issue by ZhichaoOuyang** [zhangj111/rencos#4]
I want to use my own dataset to run this model.
so could you give me the code of how how to generate rain/test.ast.src.
Thank you very much.

**Comment by ZhichaoOuyang** [comment]
Hope you can help me.

**Comment by zhangj111** [comment]
Hi,

Please refer to the code in #6 .

**Comment by ZhichaoOuyang** [comment]
got it！Thanks
