### ISSUE TITLE
可以提供一个如何生成python数据集对应的AST的代码吗

### ISSUE THREAD

**Issue by ZhichaoOuyang** [zhangj111/rencos#6]
https://docs.python.org/2/library/ast.html
这个可以提供一下代码吗

**Comment by satinewee** [comment]
> 
> 
> https://docs.python.org/2/library/ast.html
> 这个可以提供一下代码吗

请问最后是怎么解决的呀 我也遇到这个问题了

**Comment by zhangj111** [comment]
Hi,

It seems that this is a common problem, so I paste the code for parsing python dataset here. Hope it helps.

```
def parse_python(code):
    import ast,re, asttokens
    def str_node(node):
        if isinstance(node, ast.AST):
            fields = [(name, str_node(val)) for name, val in ast.iter_fields(node) if isinstance(val, str)]
            name = fields[0][1] if fields else ''
            rv = '%s %s' % (node.__class__.__name__, name.replace('\'', ''))
            return rv
        else:
            return repr(node)

    def ast_visit(node, level=0):
        tokens.extend(str_node(node).split())
        # print(str_node(node))
        for field, value in ast.iter_fields(node):
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, ast.AST) and not isinstance(item, ast.Load) and not isinstance(item, ast.Store):
                        ast_visit(item, level=level + 1)
            elif isinstance(value, ast.AST) and not isinstance(value, ast.Load) and not isinstance(value, ast.Store):
                ast_visit(value, level=level + 1)
        return tokens
    code = re.sub(r"\t", r"\\t", code)
    code = re.sub(r"\n", r"\\n", code)
    code = re.sub(r"DCNL\sDCSP", "\n", code)
    code = re.sub(r"DCNL\s\s", "\n", code)
    code = re.sub(r"DCNL\s", "\n", code)
    code = re.sub(r"DCSP", '', code)
    # print(code)
    tokens = []
    try:
        tree = ast.parse(code)
        ast_visit(tree)
        return ' '.join(tokens)
    except SyntaxError:
        print('Error')
        return 'Error'
```

**Comment by ZhichaoOuyang** [comment]
got it

**Comment by satinewee** [comment]
Thank you very much!!
But I have another question about the java dataset. I can’t use javalang to parse it.Could you please paste the code about how to parse it?
I am very grateful!!





------------------ 原始邮件 ------------------
发件人: zhangj111 <notifications@github.com&gt;
发送时间: 2020年12月24日 14:44
收件人: zhangj111/rencos <rencos@noreply.github.com&gt;
抄送: satinewee <3248777@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[zhangj111/rencos] 可以提供一个如何生成python数据集对应的AST的代码吗 (#6)





 
Hi,
 
It seems that this is a common problem, so I paste the code for parsing python dataset here. Hope it helps.
 `def parse_python(code):
 import ast,re, asttokens
 def str_node(node):     if isinstance(node, ast.AST):         fields = [(name, str_node(val)) for name, val in ast.iter_fields(node) if isinstance(val, str)]         name = fields[0][1] if fields else ''         rv = '%s %s' % (node.__class__.__name__, name.replace('\'', ''))         return rv     else:         return repr(node) def ast_visit(node, level=0):     tokens.extend(str_node(node).split())     # print(str_node(node))     for field, value in ast.iter_fields(node):         if isinstance(value, list):             for item in value:                 if isinstance(item, ast.AST) and not isinstance(item, ast.Load) and not isinstance(item, ast.Store):                     ast_visit(item, level=level + 1)         elif isinstance(value, ast.AST) and not isinstance(value, ast.Load) and not isinstance(value, ast.Store):             ast_visit(value, level=level + 1)     return tokens code = re.sub(r"\t", r"\\t", code) code = re.sub(r"\n", r"\\n", code) code = re.sub(r"DCNL\sDCSP", "\n", code) code = re.sub(r"DCNL\s\s", "\n", code) code = re.sub(r"DCNL\s", "\n", code) code = re.sub(r"DCSP", '', code) # print(code) tokens = [] try:     tree = ast.parse(code)     ast_visit(tree)     return ' '.join(tokens) except SyntaxError:     print('Error')     return 'Error'`

**Comment by zhangj111** [comment]
@satinewee 
For people who need to parse the Java dataset, please see the code below.
```
def parse_java(code):
    import javalang
    from javalang.ast import Node

    def get_token(node):
        token = ''
        if isinstance(node, str):
            token = node.replace('\"|\'', '')
        elif isinstance(node, set):
            token = 'Modifier'  # node.pop()
        elif isinstance(node, Node):
            token = node.__class__.__name__

        return token

    def get_children(root):
        if isinstance(root, Node):
            children = root.children
        elif isinstance(root, set):
            children = list(root)
        else:
            children = []

        def expand(nested_list):
            for item in nested_list:
                if isinstance(item, list):
                    for sub_item in expand(item):
                        yield sub_item
                elif item:
                    yield item

        return list(expand(children))

    def get_sequence(node, sequence):
        token, children = get_token(node), get_children(node)
        sequence.append(token)

        for child in children:
            get_sequence(child, sequence)

    tokens = javalang.tokenizer.tokenize(code)
    parser = javalang.parser.Parser(tokens)
    tree = parser.parse_member_declaration()
    seq = []
    get_sequence(tree, seq)
    return ' '.join(seq)
```
